FROM docker.io/library/python:3.8-slim@sha256:23252009f10b4af8a8c90409c54a866473a251b001b74902f04631dd54cfccc8

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -e .

EXPOSE 80

# Default to running the web server
CMD ["python", "-m", "demo", "server", "--port", "80"]